import React, { useState, useEffect } from 'react';
import { Modal } from '@/components/ui/Modal';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import type { UnifiedProvider } from '@/types/unified';
import { IconPlus, IconTrash2 } from '@/components/ui/icons';

interface CredentialEditModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (provider: UnifiedProvider) => void;
  initialData?: UnifiedProvider | null;
}

export const CredentialEditModal: React.FC<CredentialEditModalProps> = ({
  isOpen,
  onClose,
  onSave,
  initialData,
}) => {
  const [formData, setFormData] = useState<Partial<UnifiedProvider>>({
    enabled: true,
    priority: 10,
    weight: 10,
    type: 'gemini',
    credentials: {},
    tags: []
  });

  const [tagInput, setTagInput] = useState('');
  const [apiKey, setApiKey] = useState('');

  useEffect(() => {
    if (initialData) {
      setFormData(JSON.parse(JSON.stringify(initialData)));
      setApiKey(initialData.credentials?.['api_key'] || '');
    } else {
      setFormData({
        id: '', // New ID will be generated by backend or here? Better backend logic but for now let's leave empty? Or generate UUID? 
        // Backend usually handles ID generation if empty, but UnifiedProvider struct might require valid ID for updates.
        // For new create, empty ID is fine if backend handles it.
        enabled: true,
        priority: 10,
        weight: 10,
        type: 'gemini',
        credentials: {},
        tags: []
      });
      setApiKey('');
    }
  }, [initialData, isOpen]);

  const handleSave = () => {
    // Basic validation
    if (!formData.type) return;

    // Sync credentials
    const creds = { ...formData.credentials };
    if (apiKey) {
      creds['api_key'] = apiKey;
    }

    // For new entries, let backend handle ID generation
    // Only use provided ID if editing existing entry (initialData exists)
    let finalId = formData.id || '';
    if (!finalId && initialData) {
      // Generate ID for new entries only if editing mode
      finalId = `${formData.type}-${Date.now()}`;
    }

    onSave({
      ...formData,
      id: finalId,
      credentials: creds,
    } as UnifiedProvider);
    onClose();
  };

  const addTag = () => {
    if (!tagInput.trim()) return;
    setFormData(prev => ({
      ...prev,
      tags: [...(prev.tags || []), tagInput.trim()]
    }));
    setTagInput('');
  };

  const removeTag = (index: number) => {
    setFormData(prev => ({
      ...prev,
      tags: (prev.tags || []).filter((_, i) => i !== index)
    }));
  };

  return (
    <Modal
      open={isOpen}
      onClose={onClose}
      title={initialData ? "Edit Credential" : "Add New Credential"}
      width="600px"
    >
      <div className="space-y-4 p-2">
        {/* Basic Info Row */}
        <div className="grid grid-cols-2 gap-4">
           <div>
             <label className="block text-sm font-medium mb-1">Provider Type</label>
             <select 
               className="w-full border rounded p-2 bg-white dark:bg-gray-800 dark:border-gray-700"
               value={formData.type}
               onChange={e => setFormData({...formData, type: e.target.value})}
               disabled={!!initialData} // Lock type on edit to avoid confusion? Or allow?
             >
               <option value="gemini">Gemini</option>
               <option value="claude">Claude</option>
               <option value="openai">OpenAI</option>
               <option value="openai-compatibility">OpenAI Compatible</option>
               <option value="vertex">Vertex AI</option>
               {/* Add others as needed */}
             </select>
           </div>
           <div>
             <label className="block text-sm font-medium mb-1">ID (Optional)</label>
             <Input
                value={formData.id || ''}
                onChange={(e) => setFormData({...formData, id: e.target.value})}
                placeholder="Auto-generated if empty"
             />
           </div>
        </div>

        {/* Credentials */}
        <div className="border p-3 rounded bg-gray-50 dark:bg-gray-900 border-gray-200 dark:border-gray-700">
           <h4 className="text-sm font-semibold mb-2">Authentication</h4>
           <div>
             <label className="block text-xs text-gray-500 mb-1">API Key / Token</label>
             <Input
                type="password"
                value={apiKey}
                onChange={(e) => setApiKey(e.target.value)}
                placeholder="sk-..."
             />
           </div>
           {/* Future: Add more credential fields based on type */}
        </div>
        
        {/* Scheduling Specs */}
        <div className="grid grid-cols-2 gap-4">
           <div>
             <label className="block text-sm font-medium mb-1">Priority (Lower is higher)</label>
             <input 
                type="number" 
                className="w-full border rounded p-2 bg-white dark:bg-gray-800 dark:border-gray-700"
                value={formData.priority}
                onChange={e => setFormData({...formData, priority: parseInt(e.target.value) || 0})}
             />
           </div>
           <div>
             <label className="block text-sm font-medium mb-1">Weight (For Load Balance)</label>
             <input 
                type="number"
                className="w-full border rounded p-2 bg-white dark:bg-gray-800 dark:border-gray-700"
                value={formData.weight}
                onChange={e => setFormData({...formData, weight: parseInt(e.target.value) || 0})}
             />
           </div>
        </div>

        {/* Tags */}
        <div>
           <label className="block text-sm font-medium mb-1">Tags</label>
           <div className="flex gap-2 mb-2">
             <Input
               value={tagInput}
               onChange={(e) => setTagInput(e.target.value)}
               placeholder="Add a tag..."
               onKeyDown={(e) => e.key === 'Enter' && addTag()}
             />
             <Button variant="secondary" onClick={addTag}><IconPlus size={16} /> Add</Button>
           </div>
           <div className="flex flex-wrap gap-2">
             {(formData.tags || []).map((tag, idx) => (
                <span key={idx} className="bg-blue-100 text-blue-800 text-xs font-semibold px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 flex items-center">
                  {tag}
                  <button onClick={() => removeTag(idx)} className="ml-1 hover:text-red-600"><IconTrash2 size={12}/></button>
                </span>
             ))}
           </div>
        </div>

        {/* Proxy */}
        <div>
            <label className="block text-sm font-medium mb-1">Proxy URL (Optional)</label>
            <Input
               value={formData.proxyUrl || ''}
               onChange={(e) => setFormData({...formData, proxyUrl: e.target.value})}
               placeholder="http://proxy:port"
            />
        </div>
      
        <div className="flex justify-end gap-2 mt-4 pt-4 border-t">
          <Button variant="secondary" onClick={onClose}>Cancel</Button>
          <Button onClick={handleSave}>Save Credential</Button>
        </div>
      </div>
    </Modal>
  );
};
